default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  pool: 100
  database: thinkinfic_dev

test:
  <<: *default
  database: thinkinfic_test

production:
  <<: *default
  database: thinkinfic_prod
