development:
  google_client_id: '679181506059-i3kl448eas2fd8rh8ob36spr3rn28fda.apps.googleusercontent.com'
  google_client_secret: 'g7DnaswPjG3Ca0ZvVc4y0Ee6'
production:
  google_client_id: '679181506059-i3kl448eas2fd8rh8ob36spr3rn28fda.apps.googleusercontent.com'
  google_client_secret: 'g7DnaswPjG3Ca0ZvVc4y0Ee6'
